GroupM.AutoGrant.WebApp/Controllers/Reject1Controller.cs
using GroupM.AutoGrant.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace GroupM.AutoGrant.WebApp.Controllers
{
    public class Reject1Controller : Controller
    {
        private string passwordEncrypt = ConfigurationManager.AppSettings["PEAPI"];
        private string urlAPI = ConfigurationManager.AppSettings["URLAPI"];
        private string urlAPP = ConfigurationManager.AppSettings["URLAPP"];

        public ActionResult Index(string token)
        {
            try
            {
                string json = Crypt.Decrypt(token, passwordEncrypt);
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                RequestToken requestToken = serializer.Deserialize<RequestToken>(json);
                if (requestToken != null)
                {
                    ViewBag.Token = token;
                    ViewBag.RequestNo = requestToken.Request_No;
                    ViewBag.ApproverID = requestToken.Approver_ID;
                    ViewBag.ApproverUserID = requestToken.Approver_UserID;
                    ViewBag.DelegateUserID = requestToken.Delegate_UserID;
                    ViewBag.Message = "";
                    return View();
                }
                else
                {
                    ViewBag.Message = "Error: Token is null.";
                    return View();
                }
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                return View();
            }
        }

        [HttpPost]
        public ActionResult Index(string Token, string RequestNo, string ApproverID, string ApproverUserID, string DelegateUserID, string rdReason, string Reason, string btnCheck)
        {
            try
            {
                if (btnCheck == "Submit")
                {
                    RejectReason reject = new RejectReason();
                    reject.Request_No = RequestNo;
                    reject.Approver_ID = ApproverID;
                    reject.Approver_UserID = ApproverUserID;
                    reject.Delegate_UserID = DelegateUserID;
                    reject.Approve_Result = "RJ";
                    reject.Reject_Reason = rdReason;
                    reject.Reject_Detail = Reason;
                    JavaScriptSerializer serializer = new JavaScriptSerializer();
                    string jsonReject = serializer.Serialize(reject);
                    string tokenReject = Crypt.Encrypt(jsonReject, passwordEncrypt);
                    string urlReject = urlAPI + "RequestReject/Index?token=" + tokenReject;
                    return Redirect(urlReject);
                }
                else if (btnCheck == "Cancel")
                {
                    return RedirectToAction("Reject", "Login");
                }
                else
                {
                    string url = urlAPP + "Reject/Index?token=" + Token;
                    return Redirect(url);
                }
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                return View();
            }
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Fail()
        {
            return View();
        }
    }
}

GroupM.AutoGrant.WebApp/Views/Reject1/Fail.cshtml
@{
    ViewBag.Title = "Fail";
    Layout = "~/Views/Shared/AutoGrant_Layout.cshtml";
}

<div align="center">
    <h1>Reject Failed.</h1>
    <br />
    <img src="~/Image/Fail.png" alt="Reject Fail" width="50" height="50" />
    <br />
    <h3>@ViewBag.Detail</h3>
</div>

GroupM.AutoGrant.WebApp/Views/Reject1/Index.cshtml
@{
    ViewBag.Title = "Reject";
    Layout = "~/Views/Shared/AutoGrant_Layout.cshtml";
}

@using (Html.BeginForm("Index", "Reject1", FormMethod.Post))
{
    <div align="center">
        <input type="hidden" id="Token" name="Token" value="@(ViewBag.Token)">
        <input type="hidden" id="RequestNo" name="RequestNo" value="@(ViewBag.RequestNo)">
        <input type="hidden" id="ApproverID" name="ApproverID" value="@(ViewBag.ApproverID)">
        <input type="hidden" id="ApproverUserID" name="ApproverUserID" value="@(ViewBag.ApproverUserID)">
        <input type="hidden" id="DelegateUserID" name="DelegateUserID" value="@(ViewBag.DelegateUserID)">
        <input type="hidden" id="btnCheck" name="btnCheck" value="">
        <h2>Select reason for rejecting this request..</h2>
        <table>
            <tr>
                <td>
                    <input type="radio" id="R1" name="rdReason" value="Reason 1 (เหตุผล 1)" onclick="checkReason()">
                    @Html.Label("Reason 1 (เหตุผล 1)", new { style = "font-family: 'Microsoft Sans Serif'; font-size: 10pt;" })
                </td>
            </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr>
                <td>
                    <input type="radio" id="R2" name="rdReason" value="Reason 2 (เหตุผล 2)" onclick="checkReason()">
                    @Html.Label("Reason 2 (เหตุผล 2)", new { style = "font-family: 'Microsoft Sans Serif'; font-size: 10pt;" })
                </td>
            </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr>
                <td>
                    <input type="radio" id="RO" name="rdReason" value="Other - Please specify" onclick="checkReason()">
                    @Html.Label("Other - Please specify", new { style = "font-family: 'Microsoft Sans Serif'; font-size: 10pt;" })
                </td>
            </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr>
                <td>
                    @Html.TextArea("Reason", new { style = "width: 300px; height: 60px;" })
                </td>
            </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr>
                <td align="right">
                    <input type="submit" id="btnSubmit" value="✓  SUBMIT" style="background-color: mediumseagreen; color: white; border: none; padding: 5px 8px; display: inline-block" onclick="fCheck()" />
                    <input type="submit" id="btnCancel" value="✗  CANCEL" style="background-color: crimson; color: white; border: none; padding: 5px 8px; display: inline-block" onclick="fCancel()" />
                </td>
            </tr>
        </table>
        <script type="text/javascript">
            function checkReason() {
                var r1 = document.getElementById("R1").checked;
                var r2 = document.getElementById("R2").checked;
                if (r1 == true || r2 == true) {
                    document.getElementById("Reason").value = "";
                    document.getElementById("Reason").disabled = true;
                }
                else {
                    document.getElementById("Reason").disabled = false;
                }
            }
            function fCheck() {
                var ro = document.getElementById("RO").checked;
                var rs = document.getElementById("Reason").value;
                if (ro == true && rs == "") {
                    document.getElementById("btnCheck").value = "X";
                    alert("Please input your reason.");
                }
                else {
                    document.getElementById("btnCheck").value = "Submit";
                }
            }
            function fCancel() {
                document.getElementById("btnCheck").value = "Cancel";
            }
            window.onload = function () {
                var msg = "@ViewBag.Message";
                if (msg != "") {
                    alert(msg);
                }
            };
        </script>
    </div>
}

GroupM.AutoGrant.WebApp/Views/Reject1/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/AutoGrant_Layout.cshtml";
}

<div align="center">
    <img src="~/Image/reject success.jpg" alt="Approve Success" width="240" height="220" />
    <br />
    <h1>The Request was successfully rejected.</h1>
    <br />
    Thank you.
</div>